// Shelf item model + constructors + eviction. Ports src-js/store/shelf.ts semantics.
// The Slint `ShelfItemData` struct is generated by include_modules! in main.rs.

use std::cell::RefCell;
use std::path::Path;
use std::rc::Rc;
use std::sync::atomic::{AtomicI32, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

use slint::{Image, Model, ModelRc, VecModel};

use crate::ShelfItemData;

static NEXT_ID: AtomicI32 = AtomicI32::new(1);

fn alloc_id() -> i32 {
    NEXT_ID.fetch_add(1, Ordering::Relaxed)
}

fn now_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

fn file_name(path: &str) -> String {
    path.rsplit(|c| c == '/' || c == '\\')
        .next()
        .unwrap_or(path)
        .to_string()
}

fn ext_badge(path: &str) -> String {
    Path::new(path)
        .extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_uppercase())
        .unwrap_or_default()
}

/// Truncate a &str to at most `max` chars on a char boundary; returns (slice, was_truncated).
fn truncate_chars(s: &str, max: usize) -> (String, bool) {
    if s.chars().count() <= max {
        (s.to_string(), false)
    } else {
        (s.chars().take(max).collect(), true)
    }
}

fn empty() -> ShelfItemData {
    ShelfItemData {
        id: alloc_id(),
        kind: Default::default(),
        path: Default::default(),
        text: Default::default(),
        url: Default::default(),
        thumb: Image::default(),
        has_thumb: false,
        display: Default::default(),
        ext: Default::default(),
        filename: Default::default(),
        truncated: false,
    }
}

pub fn make_file(path: &str) -> ShelfItemData {
    ShelfItemData {
        kind: "file".into(),
        path: path.into(),
        ext: ext_badge(path).into(),
        filename: file_name(path).into(),
        ..empty()
    }
}

pub fn make_image(path: &str) -> ShelfItemData {
    ShelfItemData {
        kind: "image".into(),
        path: path.into(),
        filename: file_name(path).into(),
        ..empty()
    }
}

pub fn make_text(text: &str) -> ShelfItemData {
    let (preview, truncated) = truncate_chars(text, 140);
    ShelfItemData {
        kind: "text".into(),
        text: text.into(),
        display: preview.into(),
        truncated,
        ..empty()
    }
}

pub fn make_url(url: &str) -> ShelfItemData {
    let stripped = url
        .strip_prefix("https://")
        .or_else(|| url.strip_prefix("http://"))
        .unwrap_or(url);
    let (display, _) = truncate_chars(stripped, 55);
    ShelfItemData {
        kind: "url".into(),
        url: url.into(),
        display: display.into(),
        ..empty()
    }
}

/// Owns the Slint VecModel plus parallel created-at timestamps for TTL eviction.
pub struct Shelf {
    model: Rc<VecModel<ShelfItemData>>,
    created: RefCell<Vec<(i32, u64)>>, // (id, created_ms)
}

impl Shelf {
    pub fn new() -> Rc<Self> {
        Rc::new(Self {
            model: Rc::new(VecModel::default()),
            created: RefCell::new(Vec::new()),
        })
    }

    pub fn model_rc(&self) -> ModelRc<ShelfItemData> {
        self.model.clone().into()
    }

    /// Find an existing item that is the "same" as `item` (path for file/image, url for url,
    /// text for text) and return its id.
    fn duplicate_id(&self, item: &ShelfItemData) -> Option<i32> {
        (0..self.model.row_count()).find_map(|i| {
            let r = self.model.row_data(i)?;
            let same = match item.kind.as_str() {
                "url" => !item.url.is_empty() && r.url == item.url,
                "text" => !item.text.is_empty() && r.text == item.text,
                _ => !item.path.is_empty() && r.path == item.path,
            };
            if same {
                Some(r.id)
            } else {
                None
            }
        })
    }

    /// Add to the TOP of the list. If the same item already exists, remove it first so the new
    /// one appears at the top (move-to-top on re-add).
    pub fn add(&self, item: ShelfItemData) -> i32 {
        if let Some(existing) = self.duplicate_id(&item) {
            self.remove(existing);
        }
        let id = item.id;
        self.created.borrow_mut().insert(0, (id, now_ms()));
        self.model.insert(0, item);
        id
    }

    fn index_of(&self, id: i32) -> Option<usize> {
        (0..self.model.row_count()).find(|&i| self.model.row_data(i).map(|r| r.id) == Some(id))
    }

    pub fn remove(&self, id: i32) {
        if let Some(idx) = self.index_of(id) {
            self.model.remove(idx);
        }
        self.created.borrow_mut().retain(|(cid, _)| *cid != id);
    }

    pub fn reorder(&self, from: usize, to: usize) {
        let n = self.model.row_count();
        if from >= n || to >= n || from == to {
            return;
        }
        if let Some(row) = self.model.row_data(from) {
            self.model.remove(from);
            self.model.insert(to, row);
        }
    }

    pub fn clear(&self) {
        self.model.set_vec(Vec::new());
        self.created.borrow_mut().clear();
    }

    pub fn set_thumb(&self, id: i32, image: Image) {
        if let Some(idx) = self.index_of(id) {
            if let Some(mut row) = self.model.row_data(idx) {
                row.thumb = image;
                row.has_thumb = true;
                self.model.set_row_data(idx, row);
            }
        }
    }

    /// Remove items older than ttl_ms (ports eviction.ts; default 15 min).
    pub fn clear_expired(&self, ttl_ms: u64) {
        let now = now_ms();
        let expired: Vec<i32> = self
            .created
            .borrow()
            .iter()
            .filter(|(_, ts)| now.saturating_sub(*ts) >= ttl_ms)
            .map(|(id, _)| *id)
            .collect();
        for id in expired {
            self.remove(id);
        }
    }
}
